services:  
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234    
    ports:
      - 1434:1433
    networks:
     - backend  
networks:
  backend:
    name: backend
    driver: bridge

